### ISSUE TITLE
add: make fixed header component 

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher-website#1]
|                                          Desktop-tablet view                                          |                                         Mobile view                                        |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| ![](https://user-images.githubusercontent.com/86405648/195594579-76cba0b9-cbba-4e0f-ad95-0b9a12c8e32c.png) | ![](https://user-images.githubusercontent.com/86405648/195594741-e849ea2f-7878-429d-9a64-f80aab623ca5.png) |

For Now, you can skip the granular texture in the background.

**Font used**: Poppins (throughout the website ), Cairo (Star-us button)

**Steps:**

- Add changes in `src/components/Header/`

- add CSS file in the specific component directory if necessary

**Comment by mittalvansh** [comment]
Can I work on this?

**Comment by Waishnav** [comment]
I've assigned this issue to you. You can now work on this.
If you want any help then do ask it here.
Also, you can have a look at figme-design [here](https://www.figma.com/file/rzcY2XcaVMK0PGp9MmuOtF/Watcher-website?node-id=0%3A1l).

**Comment by mittalvansh** [comment]
Please Provide svg file of the arrow near Watcher!

**Comment by Waishnav** [comment]
up-arrow.svg =>   ![up-arrow](https://user-images.githubusercontent.com/86405648/195695270-ae605a71-c64d-4587-8154-3af03f8a8365.svg)
