### ISSUE TITLE
Add guidelines contributing.md

### ISSUE THREAD

**Issue by Ni-vik** [Waishnav/Watcher-website#10]
I clicked on contributing.md but it is empty. We need to add instructions in the file

**Comment by Waishnav** [comment]
CONTRIBUTING.md is mentioned in the README.md of Watcher.
Instead, we can have a section in README for contribution instructions and guidelines,
as there are pretty few instruction imo

**Comment by starohit** [comment]
assign me

**Comment by Ni-vik** [comment]
> CONTRIBUTING.md is mentioned in the README.md of Watcher. Instead, we can have a section in README for contribution instructions and guidelines, as there are pretty few instruction imo



> CONTRIBUTING.md is mentioned in the README.md of Watcher. Instead, we can have a section in README for contribution instructions and guidelines, as there are pretty few instruction imo

Okay. I will add contribution guidelines in the readme
