### ISSUE TITLE
fix: star-us button not getting disappear in mobile version.

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher-website#13]

**Comment by Waishnav** [comment]
Also, do make Watcher-logo and Watcher (container_1) anchor tags.

**Comment by mittalvansh** [comment]
can i work on this?

**Comment by mittalvansh** [comment]
As I am already dealing with logo animation, it will be easy for me to do this also!

**Comment by Waishnav** [comment]
#16 solved this issue. sorry for not merging it was a mistake made by @mittalvansh and he fixed his mistake in his new PR.
