### ISSUE TITLE
Add: Hero section

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher-website#2]
![image](https://user-images.githubusercontent.com/86405648/195699736-d8f56ecd-40b1-48c2-aac3-d645522539f1.png)

 `Get it Now` button will display the instructions to install [Watcher](https://github.com/waishnav/watcher).
 The style of the get-it button is primary. so you can give the CSS class primary-button to it.
 
You can have a look at figme-design [here](https://www.figma.com/file/rzcY2XcaVMK0PGp9MmuOtF/Watcher-website?node-id=0%3A1l).

**Assets**
![]()

|                                          Asset-name                                     |                                         Asset                                          |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| glowy-laptop-screen.svg  | ![](https://user-images.githubusercontent.com/86405648/195700055-bdc96121-f816-4aa1-b7c8-9040f5ec58f6.svg) |

**Comment by DarkSoul26** [comment]
@Waishnav I would like to contribute to this issue, please assign it to me.

**Comment by Waishnav** [comment]
@DarkSoul26 You can work on this issue.
if any asset is not given then feel free to ask for it here.

**Comment by Waishnav** [comment]
If you want any help then do ask it here.
Also, you can get some help by looking at figme-design [here](https://www.figma.com/file/rzcY2XcaVMK0PGp9MmuOtF/Watcher-website?node-id=0%3A1l).

**Comment by DarkSoul26** [comment]
Hey @Waishnav sorry for the late reply, can you provide resources for connecting to the backend?

**Comment by Waishnav** [comment]
@DarkSoul26 
For now we are just making landing page of it, so that people get aware about screen time and importance of screen time app. 
We are not making full featured web-app which will store the users data and showcase usage on their profile.

**Comment by DarkSoul26** [comment]
Got it.

**Comment by Waishnav** [comment]
Any updates @DarkSoul26

**Comment by DarkSoul26** [comment]
Need to implement from the start, so I'm working on the same.

**Comment by Waishnav** [comment]
@DarkSoul26 I'm unassigning to you as it's already late for such small issue.
As we need to complete this site as quicker as possible.

**Comment by prajjwalkapoor** [comment]
hey! I wanna work on this issue. Can you assign me this?

**Comment by Waishnav** [comment]
Sure go head...
