### ISSUE TITLE
add background grainy-effect image to body in index.css

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher-website#5]
Use the following asset and add to the `src/asset` folder and use it as a repeated bg in the body.

**grainy-effect.png**
![grainy-effect](https://user-images.githubusercontent.com/86405648/195919846-0627490a-1536-4e5c-a3b2-8822e796a1f5.png)

**Comment by amardeep911** [comment]
Plz assign this to me

**Comment by mittalvansh** [comment]
Can i work on this!

**Comment by Waishnav** [comment]
> Plz assign this to me

@amardeep911 
can you do it quicker??
For reference, you can checkout hacktoberferst website for grany-effect. 
https://hacktoberfest.com
