### ISSUE TITLE
feat: add sublte animation on watcher-logo 

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher-website#6]
As the position of the cursor changes, The eyes in the logo should move accordingly.

![image](https://user-images.githubusercontent.com/86405648/195923861-154283f4-7e63-4208-92d2-ab52804bf442.png)

For reference have a look below.
https://www.seanhalpin.design/
https://omthakare16.github.io/Nezuko-movin-eyes/

**Comment by mittalvansh** [comment]
Can I work on this!
