### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by Matthieu-ui** [Waishnav/Watcher-website#8]
Assign to follow design displayed?

**Comment by Waishnav** [comment]
You can work on the footer component.
For design, you can look up design [here](https://www.figma.com/file/rzcY2XcaVMK0PGp9MmuOtF/Watcher-website?node-id=0%3A1)

For now, just make desktop/laptop version. You can skip the mobile responiveness.

**Comment by Waishnav** [comment]
![image](https://user-images.githubusercontent.com/86405648/196007259-a35911af-e91c-4ab7-b0fc-74973450bf65.png)
@Matthieu-ui 
Also, skip the section divider shown in the upper part.

**Comment by Matthieu-ui** [comment]
Gotcha!

**Comment by Waishnav** [comment]
any updates @Matthieu-ui

**Comment by Matthieu-ui** [comment]
I'll send a PR! I have been caught up with some stuff :)

**Comment by Waishnav** [comment]
Cool
